<div id="search-export">
    <figure style="text-align:center; margin:0;"><img src="<?php echo site_url('assets/images/logo.png'); ?>" alt="Logo" height="50" /></figure>
    <div style="text-align:center; margin:30px 0 40px;">Date: <?php echo date('d-F-Y'); ?></div>
</div>

<?php if (!empty($record_list)){ ?>
<table cellpadding="0" cellspacing="0" style="width:100%; font-size:10px; margin-bottom: 20px; table-layout: fixed;">
    <thead>
        <tr style="width:100%; font-size:10px; background-color:#CCC;">
            <td colspan="2" style="padding:5px 10px; font-size:15px; font-weight:800; margin:20px 0 50px;">CLIENT INFORMATION</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding:10px 0 10px 6px; width: 50%;"><strong>Name:</strong> <?php echo $record_list->name; ?></td>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Mobile #:</strong> <?php echo $record_list->mobile; ?></td>
        </tr>
        <tr>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Email Address:</strong> <?php echo $record_list->email_address; ?></td>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>City:</strong> <?php echo $record_list->city; ?></td>
        </tr>
    </tbody>
</table>

<table cellpadding="0" cellspacing="0" style="width:100%; font-size:10px; table-layout: fixed;">
    <thead>
        <tr style="width:100%; font-size:10px; background-color:#CCC;">
            <td colspan="2" style="padding:5px 10px; font-size:15px; font-weight:800; margin:20px 0 50px;">PROJECT INFORMATION</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding:10px 0 10px 6px; width: 50%;"><strong>Project Name:</strong> <?php echo $record_list->project_name; ?></td>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Property Type:</strong> <?php echo property_types($record_list->property_type); ?></td>
        </tr>
        <tr>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Unit Number:</strong> <?php echo $record_list->unit_number; ?></td>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Payment Type:</strong> <?php echo payment_type($record_list->payment_type); ?></td>
        </tr>
        <tr>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Unit Price:</strong> <?php echo $record_list->unit_price; ?></td>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Discount Amount:</strong> <?php echo $record_list->discount_amount; ?></td>
        </tr>
        <tr>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Settled Price:</strong> <?php echo $record_list->settled_price; ?></td>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Received Amount:</strong> <?php echo $record_list->received_amount; ?></td>
        </tr>
        <tr>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Balance Amount:</strong> <?php echo $record_list->balance_amount; ?></td>
            <td style="padding:6px 0 10px 6px; width: 50%;"><strong>Balance Payment Deadline:</strong> <?php echo $record_list->balance_payment_deadline; ?></td>
        </tr>
    </tbody>
</table>
<?php } ?>

<div style="font-size:9px; font-style:italic; text-align:center; margin-top:30px;">*This statement is generated by the system and does not require a signature or stamp*</div>
